// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebService.Data;

namespace WebService.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Comparison_Engine.Base_Classes.Bar", b =>
                {
                    b.Property<int>("barID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("barLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("barName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("barID");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("Comparison_Engine.Base_Classes.Drink", b =>
                {
                    b.Property<int>("drinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("drinkName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("drinkID");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("WebService.Base_Classes.SpecificPrice", b =>
                {
                    b.Property<int>("BarID")
                        .HasColumnType("int");

                    b.Property<int>("DrinkID")
                        .HasColumnType("int");

                    b.Property<float>("DrinkPrice")
                        .HasColumnType("real");

                    b.ToTable("SpecificPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
